In [3]:
import numpy as np


In [4]:
t = np.array([[[23,50], [7, 12]],
              [[57, 67], [99, 43]],
              [[75, 21], [57, 12]],
              [[87, 26], [18, 84]]])

t

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

In [5]:
a = np.array([[23, 50, 19],
              [7, 12, 109],
              [57, 67, 98]])

b = np.array([[17],
              [22],
              [19]])

a * b

array([[ 391,  850,  323],
       [ 154,  264, 2398],
       [1083, 1273, 1862]])

In [20]:
A = np.array([[23, 50, 19],
              [7, 12, 109],
              [57, 67, 98]])
print(A.T)
print("")
print(np.linalg.det(A))
print("")
print(np.linalg.inv(A))

[[ 23   7  57]
 [ 50  12  67]
 [ 19 109  98]]

131344.0000000002

[[-0.0466485  -0.02761451  0.03975819]
 [ 0.04208034  0.00891552 -0.01807467]
 [-0.00163692  0.0099662  -0.00056341]]
[[ 23.  50.  19.]
 [  7.  12. 109.]
 [ 57.  67.  98.]]
